import { createI18n } from 'vue-i18n';
const messages = {
    en: {
        greeting: 'Hello',
        about: 'About Me',
        projects: 'Projects',
        contact: 'Contact',
        home: 'Home',
        LOGIN: 'login',
        REGISTER: 'Register',
        LOGIN_INTO_ACCOUNT: 'Log in to your account',
        ENTER_EMAIL_PASSWORD: 'Enter your email and password below to log in',
        EMAIL_ADDRESS: 'Email address',
        PASSWORD: 'Password',
        REMEMBER_ME: 'Remember me',
        DONT_HAVE_ACCOUNT: "Don't have an account?",
        FORGET_PASSWORD: ' Forgot password?',
        CREATE_ACCOUNT: 'Create an account',
        ENTER_DETAILS: 'Enter your details below to create your account',
        NAME: 'Name',
        FULL_NAME: 'Full name',
        CONFIRM_PASSWORD: 'Confirm password',
        HAVE_ACCOUNT: 'Already have an account?',
        SETTINGS: 'Settings',
        LOGOUT: 'Logout',
        VIEW_PROJECTS: 'View Projects',
        DOWNLOAD_CV: 'Download CV',
        CONTACT_ME: 'Contact Me',
        HELLO_INTRO: "Hello, I'm",
        MY_NAME: 'Eslam Kamel',
        MY_TECH_STACK: 'My Tech Stack',
        TECH_STACK_INTRO:
            'As a Full-Stack Developer, I specialize in building robust web and mobile applications using modern technologies. My core stack includes Laravel, Livewire, Vue, Nuxt.js, and Flutter.',
    },
    ar: {
        greeting: 'مرحبا',
        about: 'عني',
        projects: 'مشاريعي',
        contact: 'اتصل بي',
        home: 'الرئيسية',
        LOGIN: 'تسجيل الدخول',
        REGISTER: 'تسجيل حساب جديد',
        LOGIN_INTO_ACCOUNT: 'سجّل الدخول إلى حسابك',
        ENTER_EMAIL_PASSWORD: 'أدخل بريدك الإلكتروني وكلمة المرور للدخول',
        EMAIL_ADDRESS: 'البريد الإلكتروني',
        PASSWORD: 'كلمة المرور',
        REMEMBER_ME: 'تذكرني',
        DONT_HAVE_ACCOUNT: 'ليس لديك حساب؟',
        FORGET_PASSWORD: 'نسيت كلمة المرور؟',
        CREATE_ACCOUNT: 'إنشاء حساب',
        ENTER_DETAILS: 'أدخل بياناتك لإنشاء حسابك',
        NAME: 'الاسم',
        FULL_NAME: 'الاسم الكامل',
        CONFIRM_PASSWORD: 'تأكيد كلمة المرور',
        HAVE_ACCOUNT: 'هل لديك حساب بالفعل؟',
        SETTINGS: 'الإعدادات',
        LOGOUT: 'تسجيل الخروج',
        VIEW_PROJECTS: 'عرض المشاريع',
        DOWNLOAD_CV: 'تحميل السيرة الذاتية',
        CONTACT_ME: 'اتصل بي',
        HELLO_INTRO: 'مرحبًا، أنا',
        MY_NAME: 'إسلام كامل',
        MY_TECH_STACK: 'أدواتي التقنية',
        TECH_STACK_INTRO:
            'كمطور Full-Stack، أتخصص في بناء تطبيقات الويب والجوال القوية باستخدام التقنيات الحديثة. تشمل أدواتي الأساسية Laravel، Livewire، Vue، Nuxt.js، وFlutter.',
    },
};

export default createI18n({
    legacy: false,
    locale: 'en', // default language
    fallbackLocale: 'en',
    availableLocales: ['en', 'ar'],
    globalInjection: true,
    messages,
});
